### ISSUE TITLE
add/getButton() are protected methods and can't be used in app

### ISSUE THREAD

**Issue by mattfelsen** [braitsch/ofxModal#1]
Hey, this addon is useful!

I was trying to use `confirm.getButton()` to change the labels on the confirm/cancel buttons, but because they're protected they're not accessible from the main application. Is this intended, with the idea that you subclass the modal? If so, that seems a bit overkill since I don't want any custom behavior, just changing the labels. I got around it by making the methods public.

**Comment by braitsch** [comment]
Ah great point! I just added a `setButtonLabel(string label, int buttonIndex = 0)` method that will allow you to change the label of any of the footer buttons. I think this aligns well with the current calls of `setTitle` & `setMessage`. I rather not expose `getButton` as a public method but instead encourage the use of ofxModalTheme to customize the layout & appearance of the window's base assets.

**Comment by mattfelsen** [comment]
Cool, thanks! I haven't updated yet, but will reopen if I notice anything funky. Cheers
