### ISSUE TITLE
Alert queueing not working?

### ISSUE THREAD

**Issue by mattfelsen** [braitsch/ofxModal#2]
I see a mention in the readme that calling `modal.alert()` should queue the alert to be shown after the current one, but this isn't working for me. I was trying to present a confirm dialog, and then showing an alert after with the result of an operation.

I looked into the code a bit and it looks like there's only a check to see if a modal is currently visible, but I don't see anything getting added to a `vector` or `queue`, so was wondering if this is unimplemented, a bug, me using it wrong, or what? Thanks!

**Comment by braitsch** [comment]
You should be able to queue an alert just by assigning an alert to the modal and then calling its `alert` function. Here's a slight modification of the confirm example that queues an alert to show after the confirm button is clicked.

```
void ofApp::setup()
{   
// set the message to display //
    confirm.setMessage("press 'h' to hide this window, press 's' to show it.");

// assign an alert to this confirm modal //
    confirm.setAlert(make_shared<ofxModalAlert>());

// listen for events //
    confirm.addListener(this, &ofApp::onModalEvent);

// show the window //
    confirm.show();
}

void ofApp::onModalEvent(ofxModalEvent e)
{
    if (e.type == ofxModalEvent::CANCEL){
        cout << "cancel button was selected" << endl;
    }   else if (e.type == ofxModalEvent::CONFIRM){
        cout << "confirm button was selected" << endl;
        confirm.alert("confirm button was selected");
    }
}
```

**Comment by mattfelsen** [comment]
Just got around to implementing this and it works as in your example – thanks! Just got a little confused and missed needing both an `ofxModalConfirm` and `ofxModalAlert`

I think there's a typo in the readme in the alerts section where `loginModal login;` should be `ofxModalConfirm login;`

**Comment by braitsch** [comment]
The login modal in the readme is a custom modal window that extends ofxModalWindow. I just edited the readme to hopefully make it a little easier to follow. Let me know if you have any other questions, Cheers!

**Comment by mattfelsen** [comment]
Got it, super clear now, thanks again! 😺
