### ISSUE TITLE
I also have an addon with the same name!

### ISSUE THREAD

**Issue by roymacdonald** [braitsch/ofxModal#3]
Hi,
I also have an addon called ofxModal. 
https://github.com/roymacdonald/ofxModal
It is a bit different from yours as it is intended to display any kind of drawable thing as a modal overlay.
I think we should agree on something about the naming to avoid confussion.
Btw, this addon looks great!
All the best!

**Comment by braitsch** [comment]
Hi, I think ofxModal is an appropriate name for my addon and I rather not change it as this would be inconvenient for the people that are using it. Cheers.
